spring.application.name=user

server.port=8081
spring.datasource.url=jdbc:postgresql://user-db:5432/${USER_DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
broker.queue.email.name=default.email
spring.rabbitmq.addresses=${RABBITMQ_URL}

azure.application-insights.connection-string=${APPLICATIONINSIGHTS_CONNECTION_STRING}